### ISSUE TITLE
Support python bindings

### ISSUE THREAD

**Issue by rstrudel** [conda-forge/ompl-feedstock#3]
Hello,

Thanks for providing a conda package of ompl, this is super useful. Would it be possible to add the python bindings to the build ? I am working on robotic related topics mostly using python and doing heavy computations on clusters where I do not have root access. Often, building packages from source on different clusters with specific OS and restricted rights is quite challenging so, relying on conda packages is much simpler!

cc @lesteve who works in my team at Inria and did the original work of packaging [pinocchio](https://github.com/stack-of-tasks/pinocchio/) for conda-forge (with some great help from @wolfv at the time)

Robin

**Comment by wolfv** [comment]
I’m quite confident that it’s possible! Do you want to give it a shot? You could look at openimageio feedstock on how to do it as an example :)

**Comment by lesteve** [comment]
So we gave it a shot and we are failing quite hard for now :disappointed:

I am working on this [branch](https://github.com/lesteve/ompl-feedstock/tree/weird-pypy-error)

Here is one of the problem we saw. If you have any suggestions of the top of your head, let me know otherwise I may try the conda-forge gitter channel.

I am changing meta.yaml in what seems quite an innocuous change:
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 4958d53..84adf61 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -20,10 +20,11 @@ requirements:
     - cmake
     - pkg-config
   host:
-    - boost-cpp >=1.72
+    - boost >=1.72
     - eigen
     - flann
     - libode
+    - numpy
   run:
     - libode
     - boost-cpp
```

And I get an error mentioning pypy when trying to run `conda build` ...
```
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - boost[version='>=1.72'] -> python_abi=3.8[build=*_cp38] -> pypy[version='<0a0']
```

I tried `conda create` to create a conda env with the same dependencies without any issue (so maybe this is something I am missing about `conda build`):
```
conda create -c conda-forge -n test 'boost>=1.72' eigen flann libode numpy
```


<details>

<summary>Full error</summary>


```
$ conda build -c conda-forge .
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for ompl
INFO:conda_build.metadata:Attempting to finalize metadata for ompl
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /home/lesteve/miniconda3/envs/conda-build/conda-bld/work 
  Test:
 /home/lesteve/miniconda3/envs/conda-build/conda-bld/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/lesteve/miniconda3/envs/conda-build/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:
source activate  /home/lesteve/miniconda3/envs/conda-build/conda-bld/_build_env 


Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/core/solve.py", line 150, in solve_for_diff
    force_remove)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/core/solve.py", line 249, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/core/solve.py", line 684, in _run_sat
    history_specs=ssc.specs_from_history_map)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/resolve.py", line 1189, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda/resolve.py", line 449, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - boost[version='>=1.72'] -> python_abi=3.8[build=*_cp38] -> pypy[version='<0a0']



During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lesteve/miniconda3/envs/conda-build/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 469, in main
    execute(sys.argv[1:])
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 460, in execute
    verify=args.verify, variants=args.variants)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/build.py", line 2344, in build_tree
    notest=notest,
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/build.py", line 1335, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/render.py", line 746, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/metadata.py", line 2048, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/metadata.py", line 722, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/render.py", line 527, in finalize_metadata
    exclude_pattern)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/render.py", line 412, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/render.py", line 378, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/render.py", line 154, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/lesteve/miniconda3/envs/conda-build/lib/python3.7/site-packages/conda_build/environ.py", line 759, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"pypy[version='<0a0']"}
```

</details>

**Comment by lesteve** [comment]
So it turns out that this error was due to numpy 1.11 used by default in conda build, I am going to keep trying with a `conda_build_config.yaml` that requires numpy=1.16.

```
❯ cat ~/dev/ompl-feedstock/conda_build_config.yaml
numpy:
  - 1.16
```

**Comment by wolfv** [comment]
feel free to open a PR :)

One other option would be to remove the boost requirement from this recipe I believe.

**Comment by wolfv** [comment]
or rather the `boost >= 1.72`

**Comment by lesteve** [comment]
I assumed `boost >=1.72` was there for a good reason but maybe not. I may try this as well.

To be honest, opening a PR would be a good first step even if our approach is a bit hacky.

ATM I have some compilation errors where I would need help from a C++ guru (or OMPL guru not clear yet because that may be related to the way OMPL Python bindings are automatically generated with Py++ ...).

**Comment by wolfv** [comment]
sure, feel free to open a PR ! Happy to hae a look

**Comment by joao-pm-santos96** [comment]
doesn't this help: https://github.com/ompl/conda-recipes/tree/main ?

**Comment by traversaro** [comment]
Fixed in https://github.com/conda-forge/ompl-feedstock/pull/69 with 2.0.2 .
